server:
  port: 9191

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: CONTRACT-SERVICE
          uri: lb://CONTRACT-SERVICE
          predicates:
            - Path=/contracts/**
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/posts/**
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/comments/**
        - id: CHAT-SERVICE
          uri: lb://CHAT-SERVICE
          predicates:
            - Path=/chats/**
        - id: GAME-SERVICE
          uri: lb://GAME-SERVICE
          predicates:
            - Path=/games/**
        - id: NOTIFICATION-SERVICE
          uri: lb://NOTIFICATION-SERVICE
          predicates:
            - Path=/notifications/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost