apiVersion: v1
kind: Service
metadata:
  name: gateway
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: clashbots
spec:
  type: ClusterIP
  ports:
    - name: gateway
      port: 9191
  selector:
    app: clashbots